require "weiberle.options"
require "weiberle.keymaps"
require "weiberle.plugins"
require "weiberle.colorscheme"
require "weiberle.nvim-tree"
require "weiberle.toggleterm"
require "weiberle.telescope"
require "weiberle.comment"
require "weiberle.alpha"
-- require "weiberle.autopairs"
require "weiberle.whichkey"
