require "weiberle.options"
require "weiberle.alpha"
require "weiberle.plugins"
require "weiberle.keymaps"
require "weiberle.colorscheme"
require "weiberle.nvim-tree"
require "weiberle.toggleterm"
require "weiberle.telescope"
require "weiberle.comment"
require "weiberle.treesitter"
require "weiberle.lualine"
require "weiberle.cmp"
require "weiberle.mason"
-- require "weiberle.autopairs"
require "weiberle.whichkey"

